//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int ApprovalId { get; set; }
        public string ApprovalType { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string ApprovalStatus { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<int> RequestedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
