//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public Nullable<int> Author { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string Status { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Type { get; set; }
        public Nullable<int> Order { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
