//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.Data.EntityFrameworks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SGSDBEntities : DbContext
    {
        public SGSDBEntities()
            : base("name=SGSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Approval> Approvals { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<RequestType> RequestTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<TimeSheet> TimeSheets { get; set; }
    
        public virtual ObjectResult<GetApprovals_Result> GetApprovals(Nullable<int> approvalId, Nullable<int> approverId, Nullable<int> transactionId)
        {
            var approvalIdParameter = approvalId.HasValue ?
                new ObjectParameter("ApprovalId", approvalId) :
                new ObjectParameter("ApprovalId", typeof(int));
    
            var approverIdParameter = approverId.HasValue ?
                new ObjectParameter("ApproverId", approverId) :
                new ObjectParameter("ApproverId", typeof(int));
    
            var transactionIdParameter = transactionId.HasValue ?
                new ObjectParameter("TransactionId", transactionId) :
                new ObjectParameter("TransactionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetApprovals_Result>("GetApprovals", approvalIdParameter, approverIdParameter, transactionIdParameter);
        }
    
        public virtual ObjectResult<GetRequests_Result> GetRequests(Nullable<int> requestId, string status, Nullable<int> requestTypeId, Nullable<int> requestedBy)
        {
            var requestIdParameter = requestId.HasValue ?
                new ObjectParameter("RequestId", requestId) :
                new ObjectParameter("RequestId", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(string));
    
            var requestTypeIdParameter = requestTypeId.HasValue ?
                new ObjectParameter("RequestTypeId", requestTypeId) :
                new ObjectParameter("RequestTypeId", typeof(int));
    
            var requestedByParameter = requestedBy.HasValue ?
                new ObjectParameter("RequestedBy", requestedBy) :
                new ObjectParameter("RequestedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRequests_Result>("GetRequests", requestIdParameter, statusParameter, requestTypeIdParameter, requestedByParameter);
        }
    }
}
