//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public long Id { get; set; }
        public string EmpId { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public Nullable<double> BasicRate { get; set; }
        public string ClientId { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public string TimeIn { get; set; }
        public string TimeOut { get; set; }
        public Nullable<double> RegularHours { get; set; }
        public Nullable<double> LegalHolidayOT { get; set; }
        public Nullable<double> LegalHolidayNotWorked { get; set; }
        public Nullable<double> ExcessOfLegalHolidayOT { get; set; }
        public Nullable<double> SpecialHolidayOT { get; set; }
        public Nullable<double> SpecialHolidayNotWorked { get; set; }
        public Nullable<double> ExcessOfSpecialHolidayOT { get; set; }
        public Nullable<double> AuthorizedOT { get; set; }
        public Nullable<double> RestDayOT { get; set; }
        public Nullable<double> ExcessOfRestDayOT { get; set; }
        public Nullable<double> NightDiff { get; set; }
        public Nullable<double> Late { get; set; }
        public Nullable<double> Allowance { get; set; }
        public Nullable<double> Adjustment { get; set; }
        public Nullable<double> SSSLoan { get; set; }
        public Nullable<double> PagibigLoan { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
