//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGS.Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Approvals = new HashSet<Approval>();
            this.Approvals1 = new HashSet<Approval>();
            this.Posts = new HashSet<Post>();
            this.Requests = new HashSet<Request>();
        }
    
        public int UserId { get; set; }
        public string EmployeeId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PresentAddress { get; set; }
        public string ProvincialAddress { get; set; }
        public string LandlineNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Nationality { get; set; }
        public string Ref_Name { get; set; }
        public string Ref_Address { get; set; }
        public string Ref_Relationship { get; set; }
        public string Ref_ContactNo { get; set; }
        public string TaxIdNo { get; set; }
        public string SSSNo { get; set; }
        public string HDMFNo { get; set; }
        public string PhilHealthNo { get; set; }
        public int RoleId { get; set; }
        public string Status { get; set; }
        public string EmploymentType { get; set; }
        public string Position { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Picture { get; set; }
        public string RecState { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<Approval> Approvals { get; set; }
        public virtual ICollection<Approval> Approvals1 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Role Role { get; set; }
    }
}
